config/routes.rb
Rails.application.routes.draw do
  get 'jsondata/index'
  resources :search
  resources :location
  resources :country
  get 'info_flood/index'
  root 'info_flood#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
 has_one :search
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :country
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :country
  
  def self.search(term)
    if term
      joins(:country).where('country.name LIKE ?',"%#{term}%")
    else
      all
    end
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception

def redirect_if_not_found
logger.error "Attempt to access non-existent #{request.controller_class}#{params[:id]}"
flash[:notice] = 'Sorry, but that doesn\'t exist.'
redirect_to(country_index_url)
end

def redirect_if_information_not_found
logger.error "Attempt to access non-existent #{request.controller_class}#{params[:id]}"
flash[:notice] = 'Sorry, but that doesn\'t exist.'
redirect_to(information_index_url)
end

def redirect_if_location_not_found
logger.error "Attempt to access non-existent #{request.controller_class}#{params[:id]}"
flash[:notice] = 'Sorry, but that doesn\'t exist.'
redirect_to(location_index_url)
end

end

app/controllers/country_controller.rb
class CountryController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :redirect_if_not_found
  

  # GET /country
  # GET /country.json
  def index
    @country = Country.all
    
  end

  # GET /country/1
  # GET /country/1.json
  def show
  end

  # GET /country/new
  def new
    @country = Country.new
  end

  # GET /country/1/edit
  def edit
  end

  # POST /country
  # POST /country.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /country/1
  # PATCH/PUT /country/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /country/1
  # DELETE /country/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to country_index_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def country_params
    params.require(:country).permit(:name) 
   end
  
end

app/controllers/info_flood_controller.rb
class InfoFloodController < ApplicationController
  def index
  end
end

app/controllers/jsondata_controller.rb
class JsondataController < ApplicationController
  def index
    @search = Search.all
    render json: JSON.pretty_generate(@search.as_json)
  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :redirect_if_location_not_found

  # GET /location
  # GET /location.json
  def index
    @location = Location.all
     @country = Country.all
    @location_names = []
    @country_names = []
 
    @country.each do |country|
      @country_names << country.name
    end

    @location_groups = Location.all.group('country_id').count('id')

     @locations = []
     @location_groups.each do |group|
     @locations << group[1]
   end
  end


  # GET /location/1
  # GET /location/1.json
  def show
  end

  # GET /location/new
  def new
    @location = Location.new
    @country = Country.all
  end

  # GET /location/1/edit
  def edit
    @country = Country.all
  end

  # POST /location
  # POST /location.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /location/1
  # PATCH/PUT /location/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /location/1
  # DELETE /location/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to location_index_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:long, :lat, :area, :country_id)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /search
  # GET /search.json
  
  def index
    @search = Search.search(params[:term]).paginate(page: params[:page]).order('id ASC')
    
  end

  # GET /search/1
  # GET /search/1.json
  def show
  end

  # GET /search/new
  def new
    @search = Search.new
  end

  # GET /search/1/edit
  def edit
  end

  # POST /search
  # POST /search.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /search/1
  # PATCH/PUT /search/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search/1
  # DELETE /search/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to search_index_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def search_params
      params.require(:search).permit(:long, :lat, :area, :began, :ended, :dead, :displaced, :maincause, :country_id, :term)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/country_helper.rb
module CountryHelper
end

app/helpers/info_flood_helper.rb
module InfoFloodHelper
end

app/helpers/jsondata_helper.rb
module JsondataHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/about/index.html.erb
<h1> About InfoFlood</h1>
<p> Welcome to InfoFlood, a wiki web application 
which contains historical records of floodings in places around the world</p>
<p>Please, feel free to navigate through our menu to find information about the most 
and least affected by floodings areas globally</p>
<div id='video'>
<iframe width="871" height="490" src="https://www.youtube.com/embed/-kHEI_76Bnc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
</div>

app/views/country/_form.html.erb
<%= form_with(model: country, local: true) do |form| %>
  <% if country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
        <% country.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/country/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', country_index_path %>

app/views/country/index.html.erb
<p id="notice"><%= notice %></p>

<centre><h1>Country</h1></centre>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  
  </thead>

  <tbody>
    <% @country.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><%= link_to 'Show', country %></td>
        <td><%= link_to 'Edit', edit_country_path(country) %></td>
        <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<li class="nav-item">
        <a type="button" class="btn btn-outline-primary" style="margin-left:45%;"<%= link_to 'New Country', new_country_path %></a>
</li>

<p>Download</p>

app/views/country/new.html.erb
<h1>New Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Back', country_index_path %>

app/views/country/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @country.name %>
</p>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', country_index_path %>

app/views/info_flood/index.html.erb
<div>
<table>
   <div>
  <%= image_tag("Image2.jpg", {:style => "width:100%; height:700px;"}) %> 
  </div>
  <!-- I commented the logo that is suppose to be on top of Welcome to InfoFlood-->
<!-- <div class="centered" align="centre" style="position: absolute; top: 20%; left: 50%: transform:translate(-50%,-50%);"> <%= image_tag("Logo.jpg", {:style => "width:150px; height:150px;"}) %> </div>-->
  <div class="centered" style="position: absolute;top: 40%;left: 50%;transform: translate(-50%, -50%);color:white;font-size:50px;font-family:Rockwell;">WELCOME TO INFOFLOOD</div>
</table>
</div>

<div align="center" style="margin-top:20px;">
    <h1><b>WHO WE ARE?</b></h1>
<br>    
<h6>InfoFlood is a small organization.</h6>
<h6>We provide the world with data about Floods in various countries to give the possibility of a better world.</h6>
<h6>What do we mean by a better world?</h6>
<h6>A world where we can save people from Floods and Catastrophes with the use of this Data.</h6>

    
</div>
<hr>

<div>
<br>  
<center><p>Visuals of the consequences and impact of Flooding</p></center>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active" align="center">
      <%= image_tag("SliderImage1.jpg", {:style => "width:auto; height:580px;"}) %> 
    </div>
    <div class="carousel-item" align="center">
      <%= image_tag("SliderImage2.jpg", {:style => "width:auto; height:580px;"}) %> 
    </div>
    <div class="carousel-item" align="center">
      <%= image_tag("SliderImage3.jpg", {:style => "width:auto; height:580px;"}) %> 
    </div>
    <div class="carousel-item" align="center">
      <%= image_tag("SliderImage4.jpg", {:style => "width:auto; height:580px;"}) %> 
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
 

<hr>
<br>
<center><h1><b>THOSE AFFECTED BY FLOODS</b></h1></center>
<div id='video' align="center" style"margin-top:20px;">
<iframe width="960" height="480" src="https://www.youtube.com/embed/-kHEI_76Bnc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
</div>

app/views/jsondata/index.html.erb
<h1>Jsondata#index</h1>
<p>Find me in app/views/jsondata/index.html.erb</p>

app/views/layouts/_menu.html.erb
<!--<center><table>
 
    <tr>

    


 </tr>
</table>
</center> --> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InfoFlood</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/48781063de.js"></script>
  </head>

  <body>
    
   <nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd; text-align: center;">
   
   
  <%= image_tag("Logo2.jpg", {:style => "width:120px; height:120px; margin-right:15px;"}) %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <i class="fa fa-bars" aria-hidden="true" style= "font-size: 30px;"></i>

  </button>
      
 <div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a type="button" class="btn btn-primary" style="margin-right:15px;" <%=link_to 'HOME', info_flood_index_path %></a>
      </li>
      <li class="nav-item">
        <a type="button" class="btn btn-primary" style="margin-right:15px;"<%=link_to 'STATISTICS', location_index_path %></a>
      </li>
      <li class="nav-item">
        <a type="button" class="btn btn-primary" style="margin-right:15px;"<%=link_to 'SEARCH', search_index_path %></a>
      </li>
    </ul>
  </div>
</nav>


    
    <%= render :partial=>"layouts/menu" %>

    <%= yield %>
    
    <hr>
  <footer class="footer bg-light">
    <div class="container" style="margin:20px;">
      <div class="row" align="">
        <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
          <ul class="list-inline mb-2">
            <li class="list-inline-item">
             <a><%=link_to 'HOME', info_flood_index_path %></a>
            </li>
            <li class="list-inline-item">⋅</li>
            <li class="list-inline-item">
             <a><%=link_to 'STATISTICS', location_index_path  %></a>
            </li>
            <li class="list-inline-item">⋅</li>
            <li class="list-inline-item">
              <a><%=link_to 'SEARCH', search_index_path  %></a>
            </li>
            <li class="list-inline-item">⋅</li>
            
          </ul>
          <p class="text-muted small mb-4 mb-lg-0">© InfoFlood 2020. All Rights Reserved.</p>
        </div>
        <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
          <ul class="list-inline mb-0">
            <li class="list-inline-item mr-3">
                <i class="fa fa-home" aria-hidden="true"></i>
            </li>
            <li class="list-inline-item mr-3">
                <i class="fa fa-info" aria-hidden="true"></i>
           </li>
            <li class="list-inline-item">
                <i class="fa fa-search" aria-hidden="true"></i>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/location/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% location.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :long %>
    <%= form.text_field :long %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :area %>
    <%= form.number_field :area %>
  </div>

  <div class="field">
    <%= form.label :country_id %>
    <%= form.collection_select(:country_id, @country, :id, :name ) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/location/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', location_index_path %>

app/views/location/index.html.erb
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-3d.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<center><h1>STATISTICS</h1></center>
<figure class="highcharts-figure">
    <div id="container"></div>
    <center><p class="highcharts-description">
        This chart displays 20 countries and represents the number of locations affected by floods within them.
        The X axis represents the number of locations affected and the Y axis represents the countries.
    </p>
    </center>
</figure>
<div style="height: 50px;"></div>


<figure class="highcharts-figure">
   <div id="container2" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto;"></div>
   <center><p class="highcharts-description">
        This chart displays the Top 5 countries which recorded the highest number of floods.
    </p>
   </center>
</figure>

<div style="height: 50px;"></div>

<figure class="highcharts-figure">
   <div id="container3" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto;"></div>
   <center><p class="highcharts-description">
        This chart displays the Top 10 safest countries which recorded the least number of floods.
    </p>
   </center>
</figure>
 
<script type="text/javascript">
$(function () {
var myChart = Highcharts.chart('container',{
chart: {
type: 'column'
},
"colors": [
    "#2196f3",
    "#81d4fa",
    "#4fc3f7",
    "#0d47a1",
    "#536dfe",
    "#1565c0"
  ],
title: {
text: 'Locations affected by floods'
},
xAxis: {
max: 20,    
title: {
text: 'Countries'
},
categories:  <%= raw @country_names %>
},
yAxis: {
title: {
text: 'Number of locations'
},
   tickInterval: 100
},

tooltip: {
        headerFormat: '<span style="font-size:14px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y}</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
    },
    plotOptions: {
        column: {
            pointPadding: 0.2,
            borderWidth: 0
        }
    },
series: [{
 

name: 'Locations affected by floods',
data: <%= raw @locations %>
}]
});
});



// Build the chart
var pieColors = (function () {
  var colors = [],
    base = Highcharts.getOptions().colors[0],
    i;

  for (i = 0; i < 10; i += 1) {
    // Start out with a darkened base color (negative brighten), and end
    // up with a much brighter color
    colors.push(Highcharts.Color(base).brighten((i - 3) / 7).get());
  }
  return colors;
}());


Highcharts.chart('container2', {
  chart: {
    plotBackgroundColor: null,
    plotBorderWidth: null,
    plotShadow: false,
    type: 'pie'
  },
 
  title: {
    text: 'Top 5 countries most affected by floods'
  },
  tooltip: {
    pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
  },
  plotOptions: {
    pie: {
      allowPointSelect: true,
      cursor: 'pointer',
      colors: pieColors,
      dataLabels: {
      enabled: false
      },
      showInLegend: true
    }
  },
  series: [{
    name: 'Percentage',
    colorByPoint: true,
    data: [{
      name: 'USA',
      y: 33.26,
      sliced: true,
      selected: true
    }, {
      name: 'Philippines',
      y: 12.22
    }, {
      name: 'India',
      y: 17.24
    }, {
      name: 'Indonesia',
      y: 13.97
    }, {
      name: 'China',
      y: 23.28
    }]
  }]
});

// Build the chart
Highcharts.chart('container3', {
    chart: {
        type: 'pie',
        options3d: {
            enabled: true,
            alpha: 45
        }
    },
     "colors": [
    "#90caf9",
    "#42a5f5",
    "#3f51b5",
    "#1a237e",
    "#4db6ac",
    "#009688",
    "#00695c",
    "#004d40",
    "#304ffe",
    "#00b0ff"
  ],
    title: {
        text:  'Top 10 countries least affected by floods'

    },
    plotOptions: {
        pie: {
            innerSize: 100,
            depth: 45
        }
    },
    series: [{
        name: 'No. of floods',
        data: [
            ['Libya', 1],
            ['Lithuania', 1],
            ['Latvia', 1],
            ['Bahamas', 1],
            ['Bermuda', 1],
            ['Canary Islands', 1],
            ['Caribbean', 1],
            ['Finland', 1],
            ['Iceland', 1],
            ['Estonia', 1],            
        ]
    }]
});
</script>

app/views/location/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', location_index_path %>

app/views/location/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Long:</strong>
  <%= @location.long %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @location.lat %>
</p>

<p>
  <strong>Area:</strong>
  <%= @location.area %>
</p>

<p>
  <strong>Country:</strong>
  <%= @location.country.name %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', location_index_path %>

app/views/search/_form.html.erb
<%= form_with(model: search, local: true) do |form| %>
  <% if search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
        <% search.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :long %>
    <%= form.text_field :long %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :area %>
    <%= form.number_field :area %>
  </div>

  <div class="field">
    <%= form.label :began %>
    <%= form.date_select :began %>
  </div>

  <div class="field">
    <%= form.label :ended %>
    <%= form.date_select :ended %>
  </div>

  <div class="field">
    <%= form.label :dead %>
    <%= form.number_field :dead %>
  </div>

  <div class="field">
    <%= form.label :displaced %>
    <%= form.number_field :displaced %>
  </div>

  <div class="field">
    <%= form.label :maincause %>
    <%= form.text_field :maincause %>
  </div>

  <div class="field">
    <%= form.label :country_id %>
    <%= form.text_field :country_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/search/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', search_index_path %>

app/views/search/index.html.erb
<p id="notice"><%= notice %></p>
<center>
  <h1>SEARCH FOR FLOOD INFORMATION</h1>
 <form class="form-inline my-2 my-lg-0" >
       <div class="col-sm-12">
      <%= form_tag(search_index_path, method: :get) do %>
      <%= text_field_tag :term, params[:term] %>
      <%= submit_tag 'Search' %>
    </div>
 </form>
 <% end %>
</center>
<table class="table table-bordered" style="margin-top:30px;">
  <thead class="thead-dark">
    <tr>     
     <th>Date began</th>
      <th>Country</th>
      <th>Main cause</th>
      <th>More Details</th>
    </tr>
  </thead>

  <tbody>
    <% @search.each do |search| %>
      <tr>
        <td><%= search.began %></td>
        <td><%= search.country.name %></td>
        <td><%= search.maincause %></td>
        <td><%= link_to 'More details', search %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>
<hr>

<%= will_paginate @search %>

<center>

        <a type="button" class="btn btn-primary" <%= link_to 'DISPLAY ALL COUNTRY DETAILS', jsondata_index_path %></a>

</center>

app/views/search/new.html.erb
<h1>New Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Back', search_index_path %>

app/views/search/show.html.erb
<script src='https://api.mapbox.com/mapbox.js/v3.2.1/mapbox.js'></script>
<link href='https://api.mapbox.com/mapbox.js/v3.2.1/mapbox.css' rel='stylesheet' />
 
<center>
<p>Refresh the page if at first the map doesn't appear below.</p>

<div id='map' style='width: 720px; height: 400px; '></div>
<script>
L.mapbox.accessToken = 'pk.eyJ1Ijoic25lc2hlYiIsImEiOiJjazZ0eWI2bWgwM3djM3RtczB6Zm1hajA1In0.3puNkWvosmAZdTYx2-ACcQ';
var map = L.mapbox.map('map')
    .setView([<%= @search.lat %>, <%= @search.long %>], 5)
    .addLayer(L.mapbox.styleLayer('mapbox://styles/mapbox/streets-v11'));
    var marker = L.marker([<%= @search.lat %>, <%= @search.long %>]).addTo(map);   
    
</script>
<p id="notice"><%= notice %></p>

<table border="1" class="table table-bordered">
    <thead class="thead-dark">
    <tr>
      <th>Area impacted</th>
      <th>Began</th>
      <th>Ended</th>
      <th>Deaths</th>
      <th>Number of people displaced</th>
      <th>Main cause</th>
      <th>Country</th>
     
    </tr>
  </thead>
  <tbody>
  <tr>
    
     <td>
     <p>
      <%= @search.area %>
      </p>
    </td>
    
    <td>
     <p>
      <%= @search.began %>
      </p>
    </td>
    
    <td>
     <p>
      <%= @search.ended %>
      </p>
    </td>
    
    <td>
     <p>
      <%= @search.dead %>
      </p>
    </td>
    
    <td>
     <p>
      <%= @search.displaced %>
      </p>
    </td>
    
    <td>
     <p>
      <%= @search.maincause %>
      </p>
    </td>
    
    <td>
     <p>
      <%= @search.country.name %>
      </p>
    </td>
  </tr>
  </tbody>
</table>

<!--<%= link_to 'Edit', edit_search_path(@search) %> |-->


<a type="button" class="btn btn-primary" style="align: center;"<%= link_to 'BACK', search_index_path %></a>

app/views/search/show.json.erb
{
 "latitude" : "<%= @search.lat.to_json %>"
}

app/views/search/showdisplay.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', location_index_path %>